apiVersion: batch/v1
kind: Job
metadata:
  name: ia-corr-three-class-composition
spec:
  template:
    spec:
      priorityClassName: research-low
      restartPolicy: "Never"
      containers:
        - name: ia-corr-three-class-composition
          image: ghcr.io/janpf/niaa/pytorch:latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "1"
              memory: "5Gi"
            requests:
              cpu: "1"
              memory: "5Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
            - mountPath: /dev/shm
              name: dshm
          command:
            - python3
            #- -m
            #- debugpy
            #- --listen
            #- 0.0.0.0:4444
            #- --wait-for-client
            - /workspace/analysis_code/IA_corr.py
            - --resultfile
            - /workspace/analysis/not_uploaded/IA/.scratch.ckpts.IA.pexels.scores-three.change_class.epoch-1.pth.txt
            - --score
            - composition_score
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - osse
                      - uinen
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
        - name: dshm
          emptyDir:
            medium: Memory
