FROM tiangolo/meinheld-gunicorn-flask:latest
# would've used nginx, but... https://github.com/tiangolo/meinheld-gunicorn-flask-docker#alternatives

RUN apt-get update
RUN apt-get install -y python3-gi python3-gi-cairo gegl

#ENV APP_MODULE=webserver:load_app()

COPY ./requirements-flask.txt /app
RUN pip install -r /app/requirements-flask.txt

COPY . /app
