FROM tiangolo/meinheld-gunicorn-flask:latest
# would've used nginx, but... https://github.com/tiangolo/meinheld-gunicorn-flask-docker#alternatives

RUN apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 gegl

ENV APP_MODULE=webserver:load_app()

COPY ./requirements-flask.txt /app
RUN pip install -r /app/requirements-flask.txt

COPY . /app
