FROM pytorch/pytorch:latest

RUN apt-get update
RUN apt-get install -y libgirepository1.0-dev libcairo2-dev python3-gi python3-gi-cairo gegl gir1.2-gegl-0.3

COPY ./requirements-pytorch.txt /workspace/
WORKDIR /workspace
RUN pip install -r ./requirements-pytorch.txt
