apiVersion: batch/v1
kind: Job
metadata:
  name: execute
spec:
  template:
    spec:
      restartPolicy: "Never"
      containers:
        - name: execute
          image: janpf/niaa:latest
          imagePullPolicy: "Always"
          env:
            - name: Test
              value: "Test12"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "2Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
            - mountPath: /ava
              name: ava
          command: ["python3", "-c", "print('Hello World')"]
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: ceph-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: ceph-secret
        - name: ava
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/fischer/thesis/Datasets/AVA_dataset"
            secretRef:
              name: ceph-secret
