apiVersion: batch/v1
kind: Job
metadata:
  name: image-processor-low
spec:
  parallelism: 500
  backoffLimit: 5000
  template:
    spec:
      priorityClassName: research-low
      restartPolicy: "OnFailure"
      containers:
        - name: image-processor-low
          image: janpf/niaa:flask-latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
            - mountPath: /tmp
              name: tmp-ramdisk
          command:
            - python
            - /workspace/dataset_processing/imageworker.py
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
        - name: tmp-ramdisk
          emptyDir:
            medium: Memory
