apiVersion: batch/v1
kind: Job
metadata:
  name: image-preloader
spec:
  backoffLimit: 5000
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: image-preloader
          image: janpf/niaa:flask-latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
          command:
            - python
            #- -m
            #- debugpy
            #- --listen
            #- 0.0.0.0:4444
            #- --wait-for-client
            - /workspace/dataset_processing/image_preloader.py
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
