apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdataset
spec:
  selector:
    matchLabels:
      app: redisdataset
  replicas: 1
  template:
    metadata:
      labels:
        app: redisdataset
    spec:
      restartPolicy: "Always"
      containers:
        - name: redisdataset
          image: redis:latest
          args: ["--save"]
          imagePullPolicy: "Always"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "2"
              memory: "24Gi"
            requests:
              cpu: "2"
              memory: "24Gi"
