apiVersion: batch/v1
kind: Job
metadata:
  name: train-mobilenet-classifier-completely-super-small
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "Never"
      containers:
        - name: train-mobilenet-classifier-completely-super-small
          image: janpf/niaa:pytorch-latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "16"
              memory: "180Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "16"
              memory: "180Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
            - mountPath: /dev/shm
              name: dshm
          command:
            - python3
            #- -m
            #- debugpy
            #- --listen
            #- 0.0.0.0:4444
            #- --wait-for-client
            - /workspace/SSIA/train.py
            - --styles_margin
            - "0.1"
            - --technical_margin
            - "0.2"
            - --composition_margin
            - "0.2"
            - --conv_base_lr
            - "0.00001"
            - --dense_lr
            - "0.00001"
            - --base_model
            - mobilenet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - osse
                      - uinen
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
        - name: dshm
          emptyDir:
            medium: Memory
