FROM python:3.7

# because debian only has v2.6: downloading v3
RUN echo 'deb http://download.opensuse.org/repositories/graphics:/darktable/Debian_10/ /' > /etc/apt/sources.list.d/graphics:darktable.list
RUN wget -nv https://download.opensuse.org/repositories/graphics:darktable/Debian_10/Release.key -O Release.key
RUN apt-key add - < Release.key
RUN apt-get update
RUN apt-get install -y darktable

COPY ./survey/requirements-flask.txt /app/survey/
WORKDIR /app
RUN pip install -r ./survey/requirements-flask.txt

COPY . /app

CMD ["gunicorn", "-w", "12", "-b", "0.0.0.0:5000", "survey.webserver:load_app()"]
