apiVersion: batch/v1
kind: Job
metadata:
  name: annotate
spec:
  template:
    spec:
      restartPolicy: "Never"
      containers:
        - name: annotate
          image: janpf/niaa:latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "2Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
          command:
            - python3
            - /workspace/annotate_image.py
            - --model
            - /scratch/pretrained.pkl
            - --csv
            - /scratch/AVA/AVA.txt
            - --image
            - /scratch/AVA/images/244422.jpg
            - --out
            - /scratch/out
            - --vis
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
