apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey
spec:
  selector:
    matchLabels:
      app: survey
  replicas: 1
  template:
    metadata:
      labels:
        app: survey
    spec:
      restartPolicy: "Always"
      containers:
        - name: survey
          image: janpf/niaa:flask-latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "4"
              memory: "4Gi"
          volumeMounts:
            - mountPath: /app
              name: code
            - mountPath: /data
              name: scratch
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA/edit_survey"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA/pexels"
            secretRef:
              name: studpfister-secret
