apiVersion: batch/v1
kind: Job
metadata:
  name: tartest
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "Never"
      containers:
        - name: tartest
          image: ghcr.io/janpf/niaa/general:latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
            - mountPath: /image
              name: ratar
          command:
            - sleep
            - "100000"
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
        - name: ratar
          flexVolume:
            driver: "janpf/ratarmount-driver"
            readOnly: true
            options:
              archive: "pexels/images.tar.gz"
              ceph_mount: "scratch"
      nodeSelector:
        kubernetes.io/hostname: vana
