apiVersion: batch/v1
kind: Job
metadata:
  name: train-pexels-cold
spec:
  template:
    spec:
      restartPolicy: "Never"
      containers:
        - name: train-pexels-cold
          image: janpf/niaa:pytorch-latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "24Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "24Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
            - mountPath: /dev/shm
              name: dshm
          command:
            - python3
            # - -m
            # - debugpy
            # - --listen
            # - 0.0.0.0:4444
            # - --wait-for-client
            - /workspace/model/train_pexels.py
            - --compare_opposite_polarity
            - --parameters
            - brightness
            - contrast
            - exposure
            - highlights
            - saturation
            - shadows
            - temperature
            - tint
            - vibrance
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
        - name: dshm
          emptyDir:
            medium: Memory
