apiVersion: batch/v1
kind: Job
metadata:
  name: test-ia2nima-ava-scores-one-regr
spec:
  template:
    spec:
      priorityClassName: research-med
      restartPolicy: "Never"
      containers:
        - name: test-ia2nima-ava-scores-one-regr
          image: janpf/niaa:pytorch-latest
          imagePullPolicy: "Always"
          env:
            - name: HOME
              value: "/tmp"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "64Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "64Gi"
          volumeMounts:
            - mountPath: /workspace
              name: code
            - mountPath: /scratch
              name: scratch
            - mountPath: /dev/shm
              name: dshm
          command:
            - python3
            # - -m
            # - debugpy
            # - --listen
            # - 0.0.0.0:4444
            # - --wait-for-client
            - /workspace/IA2NIMA/testAVA.py
            - --model-path
            - /scratch/ckpts/IA2NIMA/AVA/one/change_regress/epoch-149.pth
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - osse
                      - uinen
      volumes:
        - name: code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/home/stud/pfister/eclipse-workspace/NIAA"
            secretRef:
              name: studpfister-secret
        - name: scratch
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studpfister
            path: "/scratch/stud/pfister/NIAA"
            secretRef:
              name: studpfister-secret
        - name: dshm
          emptyDir:
            medium: Memory
