name: Docker Image Build

on:
  push:
    branches:
      - master

jobs:
  build_pytorch:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        run: cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u janpf --password-stdin

      - name: checkout project
        uses: actions/checkout@v2

      - name: build pytorch image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/janpf/NIAA/pytorch:latest

      - name: docker push
        run: docker push docker.pkg.github.com/janpf/NIAA/pytorch:latest

  build_flask:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        run: cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u janpf --password-stdin

      - name: checkout project
        uses: actions/checkout@v2

      - name: build flask image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/janpf/NIAA/general:latest

      - name: docker push
        run: docker push docker.pkg.github.com/janpf/NIAA/general:latest
