name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build_pytorch:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: checkout project
        uses: actions/checkout@v2

      - name: build pytorch image
        run: docker build . --file Dockerfile --tag janpf/niaa:pytorch-latest

      - name: docker push
        run: docker push janpf/niaa:pytorch-latest

  build_flask:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: checkout project
        uses: actions/checkout@v2

      - name: build flask image
        run: docker build . --file ./survey/Dockerfile --tag janpf/niaa:flask-latest

      - name: docker push
        run: docker push janpf/niaa:flask-latest

  build_related_works:
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: checkout project
        uses: actions/checkout@v2

      - name: build image
        run: docker build . --file ./related_works.dockerfile --tag janpf/niaa:related-works-latest

      - name: docker push
        run: docker push janpf/niaa:related-works-latest
