name: Docker Image CI GitHub

on:
  push:
    branches:
      - rewrite

jobs:
  build_pytorch:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: checkout project
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: pytorch.dockerfile
          push: true
          tags: ghcr.io/janpf/NIAA/pytorch:latest


  build_flask:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: checkout project
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./survey/Dockerfile
          push: true
          tags: ghcr.io/janpf/NIAA/general:latest

  build_tensorflow:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: checkout project
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: tensorflow.dockerfile
          push: true
          tags: ghcr.io/janpf/NIAA/tensorflow:latest
